# Database
spring.datasource.url=jdbc:mysql://mysql:3306/event_management_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# Mail
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# AI
ai.service.url=http://python-ai:8000/chat
ai.recommend.url=http://python-ai:8000/recommend